source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'
inhibit_all_warnings!
platform :ios, '8.0'
use_frameworks!

target 'GraduationProject' do

pod 'FDFullscreenPopGesture'

pod 'PureLayout'

pod 'Alamofire'

pod 'SwiftyJSON'

pod 'SVProgressHUD'

pod 'QMUIKit'

pod 'ObjectMapper'

pod 'Kingfisher'

pod 'AlamofireObjectMapper', '~> 5.0'

pod 'MJRefresh'

pod 'Bugly'

end
